### ISSUE TITLE
Reify folklore issues

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit#1727]
Some time ago I collected notes for the Urbit *iter technica*, a record I'd planned to make of technical matters that existed mostly in the ether around Tlon.  I eventually realised that I was trying to make a static, limited rendering of a GitHub issues database, so have since pivoted towards cleaning up and improving our issues database instead.

The idea is that the issue tracker should be a canonical and fairly comprehensive source of truth re: technical matters around Urbit.  I now think it's fine to include just about anything relevant here; in my view, said thing just has to be written to a fairly useful, informative quality.

That's all well and good.  But I still have a bunch of folklore technical notes lying around that haven't yet been reified as issues.  I know enough about some of these to expound on them on my own, but in the interest of ~~doing less work~~ crowdsourcing those more knowledgable than myself, I'm going to post some of the bullet points here.

If you know something substantial about any of these, and find yourself feeling particularly inspired, feel free to create a canonical issue about it.  Please tick off the issue below if you do.

---

* [ ] vere: inject entropy on a timer
* [ ] vere: separate terminal client
* [ ] vere: foundationdb
* [ ] vere: haskell king
* [x] hoon: compiler jets disabled and performance implications characterized
* [x] hoon: fix/use spec runes (any outstanding?)
* [x] hoon: fix/use skin runes (especially ?#)
* [ ] hoon: more efficient hoon macro expansions
* [ ] hoon: explicit type separation between natural and synthetic hoons
* [x] hoon: syntax modernization, old syntax removed from parser
* [x] hoon: fix the pronounceables
* [ ] hoon: doc-comments, stud-names, access to, &c
* [ ] hoon: space leak on |reset
* [ ] arvo: thunk effect (how to handle types?) (special vere handling for efficient event log)
* [ ] arvo: %toss / %drip (same behn efficiency questions)
* [ ] arvo: scry referential transparency (plus non-transparent version if necessary?)
* [ ] arvo: sort out the duct model
* [ ] arvo: sane vane bootstrapping (affects all vanes as well)
* [ ] arvo: neo-arvo integrated filesystem (for more robust reset/reload)
* [ ] behn: set many timers for high throughput (scry for pending timers, queue multiple wakes?)
* [ ] dill: make sessions real (requires lots of vere work to take advantage)
* [ ] eyre: find a way to serve GET requests via scry
* [ ] ford: handle |reset (and get vases out of schematics)
* [x] gall: new app interface
* [x] gall: kill bones (and specially handle cancel-able and multi-event vane moves)
* [x] gall: explicitly deferred acknowledgements
* [x] jael: eth subscription robustness
* [ ] jael: track all neighbors
* [ ] jael: lazily load pki
* [x] jael: store secrets more broadly (included ames symmetric keys)
* [ ] aqua/ph: needs more determinism

**Comment by loganallenc** [comment]
A suggestion to add:
(ford) remove marks functionality entirely

**Comment by lukestiles** [comment]
Dusting this one off after a conversation with @joemfb . Are there any other lists like this laying around?
